### ISSUE TITLE
Remove patch in favor of copying lib file

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/lcms2-feedstock#7]
In developing https://github.com/conda-forge/lcms2-feedstock/pull/6
two techniques were found to get the system compiling:
1. patching the requirement on `libtiff.lib` -> `tiff.lib`
2. temporarily copying `tiff.lib` to `libtiff.lib`

Idea #1 ended up making it in, but @isuruf believes idea 2 is easier to maintain.

We should likely revert to 2. on the next release.

**Comment by kmilos** [comment]
This should probably be done as part of the libtiff feedstock. E.g. zlib feedstock ships multiple copies of the lib under different names.
